version: 1.0.{build}

image: Visual Studio 2015

configuration: Release

build:
  parallel: true
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: false

cache:
  - Source\packages -> Source\**\packages.config

before_build:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { $env:TAG_VERSION = "$env:APPVEYOR_REPO_TAG_NAME.$env:APPVEYOR_BUILD_NUMBER" } else { $env:TAG_VERSION = "v1.0.0.$env:APPVEYOR_BUILD_NUMBER" }
  - ps: $env:TAG_VERSION = $env:TAG_VERSION -replace 'v',''
  - ps: Write-Host "Setting version to '$env:TAG_VERSION'"
  - ps: (Get-Content Source\Chattel\Properties\AssemblyInfo.cs) -replace '1\.0\.\*', "$env:TAG_VERSION" | Set-Content Source\Chattel\Properties\AssemblyInfo.cs
  - ps: (Get-Content Source\Chattel\Chattel.nuspec) -replace '0\.0\.\0', "$env:TAG_VERSION" | Set-Content Source\Chattel\Chattel.nuspec
  - nuget restore Source\Chattel.sln

after_build:
  - ps: nuget pack Source\Chattel.nuspec

deploy:
  - provider: NuGet
    name: nuget_release
    api_key:
      secure: {NuGetKey}
    skip_symbols: true
    on:
      appveyor_repo_tag: true
