version: 1.0.{build}

image: Visual Studio 2015

nuget:
  project_feed: true

configuration: Release

build:
  parallel: true
  verbosity: minimal

cache:
  - Source\packages -> Source\**\packages.config

before_build:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { $env:TAG_VERSION = "$env:APPVEYOR_REPO_TAG_NAME.$env:APPVEYOR_BUILD_NUMBER" } else { $env:TAG_VERSION = "v1.0.0.$env:APPVEYOR_BUILD_NUMBER" }
  - ps: $env:TAG_VERSION = $env:TAG_VERSION -replace 'v',''
  - ps: Write-Host "Setting version to '$env:TAG_VERSION'"
  - ps: (Get-Content Source\Chattel\Properties\AssemblyInfo.cs) -replace '1\.0\.\*', "$env:TAG_VERSION" | Set-Content Source\Chattel\Properties\AssemblyInfo.cs
  - nuget restore Source\Chattel.sln

after_build:
  - rename bin Chattel

artifacts:
  - path: Chattel
    name: chattel-dotnet
    type: Zip

