language: csharp
solution: Source/Chattel.sln

mono:
  - 4.6.1

cache:
  directories:
    - Source\packages

before_script:
  - if [ "$TRAVIS_TAG" ]; then export TAG_VERSION="$TRAVIS_TAG.$TRAVIS_BUILD_NUMBER"; else export TAG_VERSION="v1.0.0.$TRAVIS_BUILD_NUMBER"; fi
  - export TAG_VERSION=`echo $TAG_VERSION | sed 's/v//'`
  - echo "Setting version to '$TAG_VERSION'"
  - sed -i "s/1\.0\.\*/$TAG_VERSION/" Source/Chattel/Properties/AssemblyInfo.cs

before_deploy:
  - mv bin Chattel
  - zip -r Chattel-mono.zip Chattel > /dev/null

