language: csharp
solution: Chattel.sln

mono:
- 4.6.1

cache:
  directories:
  - packages

before_script:
- if [ "$TRAVIS_TAG" ]; then export TAG_VERSION="$TRAVIS_TAG.$TRAVIS_BUILD_NUMBER"; else export TAG_VERSION="v1.0.0.$TRAVIS_BUILD_NUMBER"; fi
- export TAG_VERSION=`echo $TAG_VERSION | sed 's/v//'`
- echo "Setting version to '$TAG_VERSION'"
- sed -i "s/1\.0\.\*/$TAG_VERSION/" Source/Chattel/Properties/AssemblyInfo.cs
- sed -i "s/1\.0\.\*/$TAG_VERSION/" Source/Chattel-AssetTools/Properties/AssemblyInfo.cs

before_deploy:
- mv bin Chattel-mono
- zip -r Chattel-mono.zip Chattel-mono > /dev/null

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: vIt7e/JrlL21zh3OcciR9NVKfpII50oAqTuj6IfRSZzMLJULJVTEkQXybgyUZGqQVh30VyxEnG45Km+PhXnZY0L5Qp9ydvaMk/RvXXoZYoyti9NHbJ+tUnuiByzWu8xlrqYuu0iwoiQBfZ2kmO6piPEZ8SPS795Z5XQUICYTyxQRlSSZP2b8lyg5mvl2oZm5lu2oll7Na6PT0QanCM3zafrKZha4B5QHUlHXbbq92hCqLLQlxV7b461rVMj5t32pbp9V0LtMQ/0CWKSli+1rsTNp5coTsJ9C4EuAKlmt/+XXzD+mB4rR+wTBfsGouJ22zlDp+r9rKgqlFdnr1LCmiiBcbBgD+zb3AlbPVUeQJ/5z96AFPRl+VYHBSolCm82IROTVaxB06jo5szo+8i78TOyT3cRF9JkOhXfLQrKVOE/NdZBihjnRNEM+K2V83B7nSaCszRYUqt2y7GPafcxov3eXq+ldO/ogJGS5d31buh4xHZPZe1iIUa74v6ooNd1aeP4tRBxsGOwY18MVADoiiAt4+mm7PcfQCAW8wB5ZpvZxZgMXtqLzyX4IbX4J1/cuj2vYn/dnpV0F0HWtKhT+kFYv6QWYyVpOEmKbULzq2ubY1sZasVJlJ0lvyLpQT9XeNteR3kAORAu7mGIAd6ht1rDcQmL5bC71eELIk6JBErw=
  file: Chattel-mono.zip
  draft: true
  on:
    repo: kf6kjg/chattel
    tags: true
